version: '3.8'
services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: demo_user
            POSTGRES_PASSWORD: demo_password
            POSTGRES_DB: prisma_comparison_demo
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U demo_user"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
