name: Integration Tests

on:
  workflow_dispatch:  # Manual trigger only for now
  # Temporarily disabled for PR testing
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main, develop ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: demo_user
          POSTGRES_PASSWORD: demo_password
          POSTGRES_DB: prisma_comparison_demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build packages
      run: npm run build
      
    - name: Setup integration test environment
      working-directory: ./examples/prisma-comparison-demo
      env:
        DATABASE_URL: postgresql://demo_user:demo_password@localhost:5432/prisma_comparison_demo
      run: |
        npm install
        npx prisma generate
        npx prisma db push
        npx prisma db seed
        
    - name: Run integration tests
      working-directory: ./examples/prisma-comparison-demo
      env:
        DATABASE_URL: postgresql://demo_user:demo_password@localhost:5432/prisma_comparison_demo
      run: |
        npm test
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-reports
        path: ./examples/prisma-comparison-demo/reports/
        retention-days: 30